version: '3'
services:
  redis:
    image: "redis:alpine"
  web:
    image: node:8
    user: node
    working_dir: /home/node/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=localhost
    volumes:
      - ./web:/home/node/app
    command: npm run start
  api:
    image: node:8
    user: node
    working_dir: /home/node/app
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    command: npm run start
  nginx:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    restart: always
    depends_on:
      - web
      - api
    command: [nginx-debug, '-g', 'daemon off;']
