version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
  node:
    image: node:8
    user: node
    working_dir: /home/node/app
    ports:
      - 3001:3001
      - 9229:9229  # node remote deubgging
      - 9229:9229/udp  # node remote deubgging
    environment:
      - NODE_ENV=docker
    volumes:
      - ./:/home/node/app
    command: npm run start-debug
